### ISSUE TITLE
Sandbox: Graceful Hot Reload

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#198]
Since the preview updates on every editor change, you often are in a state where there is a transpilation error until you finish typing your full change. At a minimum, render updates should be debounced. Other strategies can be considered as well

**Comment by calebjacob** [comment]
Turns out the `<Editor />` component provided by Monaco has an `onValidate` callback prop that's already debounced. Whenever it resolves, it emits an event with an array of any errors in the current document (or an empty array if it is valid). I'm going to tie into this existing event handler for updating the preview and re-compiling in a more graceful way. We may need to take things a step further, but it will provide a much better experience with little effort.

**Comment by calebjacob** [comment]
After chatting further with @mpeterdev, we decided it makes the most sense to just implement a simple 500-750ms debounce for now. We can look into making our hot reload logic more advanced down the road.
