### ISSUE TITLE
CSS rule removal is not applied

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#229]
In the sandbox on #221 , if I add a CSS rule and then remove it then I still see the styling applied in the preview

e.g. add the following rule then remove it, the elements are still purple
```
h2 {
  background-color: rebeccapurple
}
```

**Comment by andy-haynes** [comment]
I believe the issue is that CSS is assumed to be static (like Component source) and that it's safe to accumulate stylesheet rules. In sandbox this means that newer, valid rules will cancel out the previous rule but an invalid rule will just cause it to continue using the previous rule.

Should be easy to fix by attaching rules to a fixed stylesheet and making it reset-able for sandbox.

**Comment by calebjacob** [comment]
Just stumbled into this issue myself. :)
