### ISSUE TITLE
Sandbox: CSS module support

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#234]

**Comment by mpeterdev** [comment]
if the effort is reasonable, it would cool to be able to have your editor pane split between component src and css

**Comment by calebjacob** [comment]
Hey @mpeterdev @andy-haynes @pavelisnear @thisisjoshford, after starting to dig into CSS Module support for the Sandbox, here's what I'm thinking for DX and implementation:

Have separate `*.module.css` files live alongside `.tsx` component files in the file explorer tree. This would match typical React DX  when working in an IDE like VS Code:

<img width="263" alt="Screen Shot 2024-02-05 at 11 53 36 AM" src="https://github.com/near/bos-web-engine/assets/1475067/0045acc3-0ba1-4622-bdd3-1189eaaaf499">

However, it does introduce some interesting challenges in our use case since `source` and `css` are linked once published to the blockchain.

If the filenames match (eg: `MyComponent.tsx` and `MyComponent.module.css`), the Sandbox would have logic to merge the `source` and `css` together to form a single `BOSModule` when passing to the compiler (and also on publish):

```
interface BOSModule {
  component: string;
  css?: string;
}
```

Whenever creating a new component, we'd generate a `tsx` and `css` file with matching filenames. In this way, we wouldn't be allowing the developer to explicitly create different file types, which could help prevent some headaches for DX and implementation.

If a CSS Module file doesn't match a component file (due to typo, renaming, removing files), then it would be orphaned. We could implement some logic to prevent this. Whenever either the component or CSS file is renamed, we'd update both to keep them in sync. If a component file is removed, we'd also remove the corresponding CSS file.

Another option that would be a slight twist to this is hiding the file types from the file explorer entirely. There would be a single entry for `MyComponent`. When that component is selected/active, there would be some sort of tab to switch between `source` and `css`. This pattern could be interesting for more use cases down the road (metadata, documentation, etc).

Please let me know your thoughts and opinions! Thanks!

**Comment by calebjacob** [comment]
Also, one interesting difference from true CSS Modules is that we won't need the typical syntax of importing styles like so:

```tsx
import s from './MyComponent.module.css';

export function MyComponent() {
  return <div className={s.foobar}>...</div>;
}
```

You would simply write:

```tsx
export function MyComponent() {
  return <div className="foobar">...</div>;
}
```

**Comment by calebjacob** [comment]
I really like that idea @mpeterdev. I'll plan on going that route with the UX.

> The discussion has me contemplating the impact this coupling has on styles though - would we ever want to have a CSS-only SocialDB record to facilitate shared styles? The current implementation could probably support this with only minor modifications 🤔

It's a good thought. My gut reaction says that we should push developers towards only writing component scoped CSS. Global CSS can quickly get out of hand. I think our current implementation is sufficient.

> Is the typical import syntax our ideal end result? We're probably not that far off from being able to implement it.

Great question @andy-haynes. Our current implementation without the import syntax will cause some confusion to anyone used to CSS Modules. Whenever you write `className="foobar"`, it means you're using a globally declared class. Whenever you write `className={s.foobar}`, you know you're using a scoped class provided by a CSS Module that's guaranteed to not clash or inherit other styles. When using this import syntax, `s.foobar` gets mapped to a generated class name like: `my_app_foobar_123abc`.

If we could match this behavior and syntax, I think it would be a big win. We wouldn't generate any confusion and code could be much more easily pulled in or ejected to/from a traditional React codebase.

**Comment by thisisjoshford** [comment]
> I like the idea of a tight coupling between the css file and the source file, and negating any possibility of breaking the connection through renames, etc. What do you think about something along these lines where we have css files visually linked but subordinate to their component source? This improves scannability of the sidebar as well since all left aligned items are distinct components

Love the visual representation of nested `.css` files next to their `.tsx` counterpart @mpeterdev :) 

> Is the typical import syntax our ideal end result? We're probably not that far off from being able to implement it.
> > Great question @andy-haynes. Our current implementation without the import syntax will cause some confusion to anyone used to CSS Modules. Whenever you write className="foobar", it means you're using a globally declared class. Whenever you write className={s.foobar}, you know you're using a scoped class provided by a CSS Module that's guaranteed to not clash or inherit other styles. When using this import syntax, s.foobar gets mapped to a generated class name like: my_app_foobar_123abc.
> > If we could match this behavior and syntax, I think it would be a big win. We wouldn't generate any confusion and code could be much more easily pulled in or ejected to/from a traditional React codebase.

If we're not far off from implementing it I would love to have typical import syntax here. 


> My gut reaction says that we should push developers towards only writing component scoped CSS. Global CSS can quickly get out of hand. I think our current implementation is sufficient.

>  Our current implementation without the import syntax will cause some confusion to anyone used to CSS Modules. Whenever you write className="foobar", it means you're using a globally declared class. Whenever you write className={s.foobar}, you know you're using a scoped class provided by a CSS Module that's guaranteed to not clash or inherit other styles. 

@calebjacob, @andy-haynes I'm confused on if we are allowing global CSS or not. The first statement here is against global CSS but the second statement regarding our current approach sounds conflicting.

**Comment by calebjacob** [comment]
@thisisjoshford So we're not allowing truly global CSS as of right now. Any styles that are written are scoped to the current component and all its children. This is more of a short term experiment as we're figuring out how to better replicate true CSS Modules. Check this ticket out: https://github.com/near/bos-web-engine/issues/252
