### ISSUE TITLE
Use `key` instead of `id` for sibling components of the same type

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#335]
Instead of defining a new property specifically for BWE that is somewhat like React `key`, we should be able to just use `key`

There may be instances where BWE needs a `key` and React wouldn't normally require one, but React shouldn't mind if you provide a key where not strictly necessary

This also means that when rendering lists, we only need one identifying property

**Comment by andy-haynes** [comment]
This technically conflicts with #261, I'm guessing the below example is what we're after?

before
```jsx
<Message id="message" trust={{ mode: 'trusted' }} props={{ message: 'hello' }} />
```

after
```jsx
<Message key="message" bwe={{ trust: { mode: 'trusted' } }} message="hello" />
```

**Comment by mpeterdev** [comment]
correct, removing a dedicated BWE `id` property from the mental model and tying into React `key` as you've shown

any concerns with that approach?

**Comment by andy-haynes** [comment]
No issues with the syntax.

My only concern is that this could establish a false equivalence for developers, in particular the case where they mistakenly believe that two sandboxed Components whose only common ancestor is the root don't require a `key` because React wouldn't require one. I still think the convenience and clarity of using `key` for both outweighs any real problems.

Now that I think about it, with better static analysis we could generate these IDs at build time. Then the only time Components would need it specified explicitly is when React would require `key`. It's just a much bigger problem for us if they use bad `key`s 😅
