### ISSUE TITLE
Demo page code inspector panel

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#56]
Allow viewing source of components loaded by outer application in a window

Can be accomplished with a collapsible side panel, collapsible floating panel or Chrome Dev Tool panel

**Comment by mpeterdev** [comment]
Having the ability to view the source of all components currently loaded (or all that were fetched in the current page load) would be great to build support for now because it will help with debugging and demonstrations.

I am leaning towards building a custom chromium devtools panel being the best solution. While there is some overhead to putting together + publishing a chromium extension and understanding the architecture of communicating data into the panel, it has a few benefits:
1. great learning experience for whoever takes it on
2. set a foundation for proper browser dev tools which we can continually add features to and provide to the community of BOS developers
3. could likely remove the need for any in-application debug flags

For the initial version, regardless of whether this is built in-app or as a dev tool panel, I would be looking for something similar to the Sources panel in chromium dev tools with a list or tree of components as a sidebar and the source of the highlighted component as the center content.

Side note: maybe it's possible to add directly into the Sources tab even if we don't otherwise build a custom panel?

Reference: https://developer.chrome.com/docs/extensions/reference/devtools_panels/

cc @andy-haynes @calebjacob

**Comment by calebjacob** [comment]
Lots of good ideas. My only 2 cents is that a code inspector feature could be beneficial to have in the app itself for easier discoverability. There could be a bit of a barrier to installing a browser extension. That said, an actual browser devtools panel does sound cool.

**Comment by andy-haynes** [comment]
> Having the ability to view the source of all components currently loaded (or all that were fetched in the current page load)

I see a lot of devtools extensions for printing `postMessage` payloads; if the Compiler web worker sent messages for each source load, etc. then you'd be able to capture all this. An in-app implementation would work the same way. It's not the source of truth that you'd get from querying the devtools API of course, but it's a good start.

> Side note: maybe it's possible to add directly into the Sources tab even if we don't otherwise build a custom panel?

That could be a good stopgap for a devtools panel, maybe a viable alternative depending on what constraints that puts on it. It's frustrating now because you can see the iframes in the list of sources but can't view the source except in the DOM 😱. Fortunately any logs/errors from an iframe reported in the console provide a link to the breaking line within the source, at which point you can navigate the entire source for that iframe.

> My only 2 cents is that a code inspector feature could be beneficial to have in the app itself for easier discoverability.

Yeah I think at a high level there's not an _immediate_ advantage to a devtools panel. A panel will be amazing for maintainers and developers just by being a more accurate monitor, but the debugging and profiling potential would bring it to the next level 😍. But if we're only interested in metrics about the loaded and running Components right now, the in-app solution is pretty straightforward and involves the same prerequisite work of reporting worker events.
